### ISSUE TITLE
[Convenience Issue 2.0.1] Trying to access attribute of object null

### ISSUE THREAD

**Issue by Odinvt** [despark/laravel-db-localization#1]
Hi !
First of all, thank you for this awesome package. Such an obvious need and no official solution from Laravel :D .

Second of all, I added some convenience code so the Trait doesn't generate unneeded exceptions, but I didn't know if it was enough to create a pull request :D .

In File `src/Despark/LaravelDbLocalization/i18nModelTrait.php` line `105`
###### This block

``` php
if (isset($this->id) && $locale) {
        $translation = $translationModel::where($this->translatorField, $this->id)
            ->where($this->localeField, $locale)->first();
}
```
###### Should look more like this

``` php
if (isset($this->id) && $locale) {
       $translation = $translationModel::where($this->translatorField, $this->id)
           ->where($this->localeField, $locale)->first();

       if(!$translation)
           $translation = $translationModel;
}
```

Otherwise when people do something like `$contacts->translate('en')->location;` and the english translation is not available, this bit `$contacts->translate('en')` would return null because of the line `98` (`$translation = null;`) so the code would trigger an exception for trying to access attribute `location` of null object. The solution is simply to return an empty translator object instead.
###### I also added this function :

``` php
    public function getTranslatedNoIdAttributes()
    {
        $array = [];
        foreach($this->translatedAttributes as $attr) {
            if(strpos($attr, '_id') === false) {
                array_push($array, $attr);
            }
        }
        return $array;
    }
```

It returns the translatedAttributes without the model_id and the 18n_id so people can do some convenient but not so fancy stuff like this : 

``` php
    {!! Form::open(['model' => $contact, 'store' => 'admin.contacts.store', 
         'update' => 'admin.contacts.update']) !!}

        @foreach($contact->getTranslatedNoIdAttributes() as $trans_attr)
            @foreach($languages as $language)
                {!! Form::text($trans_attr.'['.$trans_attr.'_'.$language->id.']', 
                    ucfirst($trans_attr) . ' ('.$language->name.')', 
                    $contact->translate($language->id)->{$trans_attr}) !!}
            @endforeach
        @endforeach
...
```

This removes the need to update every form.blade.php everytime you add a language or a translatable field. Which was my need in the first place :p . Hope you include this to make the 2.0.2 . I would gladly update to that version ! 

Thank you again !

**Comment by tbanov** [comment]
Thank you for your positive feedback, i will add this changes to the package as soon as possible.
