### ISSUE TITLE
vendor publish error

### ISSUE THREAD

**Issue by mahezer** [despark/laravel-db-localization#2]
Hi, I'm using Laravel 5.2 and I can't run the php artisan vendor:publish command. It keeps saying: 
"Class 'Despark\LaravelDbLocalization\LaravelDbLocalizationServiceProvider' not found". I'm quite a newbie with programming, so the error should be the way I installed it.
Anyway, can you help me ?

![vendor](https://cloud.githubusercontent.com/assets/13949991/12201870/b6bba812-b60d-11e5-872c-31ea591b7b3f.png)

Thanks in advance.

**Comment by tbanov** [comment]
Currently we are supporting only 4.2 and 5.1

**Comment by mahezer** [comment]
Oh, I see. Thanks =)
